FROM mcr.microsoft.com/devcontainers/base:ubuntu@sha256:bb779775cfc7d2e65f9b0f80f17770878f5a50c00d15cc873b627c5c214ce37e

RUN apt-get update && apt-get -y install --no-install-recommends \
  build-essential clang cmake cmake-curses-gui default-jdk doxygen gfortran git graphviz \
  less libtool-bin libyajl-dev mpi-default-dev ninja-build pkg-config valgrind wget
