name: alien
on:
  workflow_dispatch:
#  schedule:
#    - cron: "7 0 * * *"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: alien
    steps:
      - name: install
        run:  |
          sudo apt-get -q update
          sudo apt install alien
      - name: test
        run:  |
          curl -s -L -O https://github.com/HDFGroup/hdf5/releases/download/snapshot/snapshot-ubuntu-2204_gcc.rpm.tar.gz
          tar zxvf snapshot-ubuntu-2204_gcc.rpm.tar.gz
          cd hdf5
          sudo alien HDF5-1.15.0-1.x86_64.rpm
          ls
          sudo dpkg -i hdf5_1.15.0-2_amd64.deb
          ls /HDF_Group/HDF5
          /HDF_Group/HDF5/1.15.0/bin/h5ls --help
