name: armv7 lin

on:
  push:
    branches:
      - develop-

permissions: read-all

jobs:
  armv7:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: Build on ubuntu-latest armv7
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
      - uses: uraimo/run-on-arch-action@fd7aa8593480287702b446a273a68f788a9bad3a # v3
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu_latest

          install: |
            apt-get update -q -y
            apt-get install -q -y git
            apt-get install -q -y cmake
          run: |
            echo ::set-output name=uname::$(uname -a)
            mkdir build
            cd build
            cmake -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF ..
            make
            ctest --timeout 3000


      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
