name: cyg ninja

on:
  push:
    branches:
      - develop-

permissions: read-all

jobs:
  test:
    name: cyg ninja
    runs-on: windows-latest
    steps:
      - name: git
        run: |
          git config --global core.autocrlf input
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: set
        uses: cygwin/cygwin-install-action@4ef15ca7fd18a18f1000989fcfd968e06d146ce8 # master
        with:
          packages: cmake gcc-fortran make ninja perl zlib-devel
      - name: test
        run: |
          export PATH=/usr/bin:$PATH
          mkdir build
          cd build
          cmake -G Ninja \
           -D SITE:STRING=cwin \
           -DBUILDNAME:STRING="ninja" \
           -D BUILD_SHARED_LIBS:BOOL=OFF \
           -D CTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
           ..
          # ctest -D Experimental
          ctest -T Build
          ctest -T Test
        shell: C:\cygwin\bin\bash.exe -eo pipefail -o igncr '{0}'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
