name: d

on:
  push:
    branches: develop-

permissions:
  contents: read

jobs:
  test: # make sure the action works on a clean machine without building
    name: ${{ matrix.os.name }} ${{ matrix.os.architecture }} ${{ matrix.os.version }} on ${{ matrix.os.host }}
    runs-on: ${{ matrix.os.host }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: openbsd
            architecture: x86-64
            version: '7.8'
            host: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - name: ${{ matrix.os.name }}
        uses: cross-platform-actions/action@b412ac9c4c4979654bb817a5d91878fdf87af740 # master
        with:
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: '${{ matrix.os.version }}'
          shell: bash
          run: |
            sudo pkg_add git
            sudo pkg_add cmake
            sudo pkg_add libaec
            export MALLOC_OPTIONS="SCFGJRU"
            mkdir build
            cd build
            cmake \
            -DBUILDNAME:STRING=hk/d \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCTEST_DROP_LOCATION_INIT="/submit.php?project=HDF5" \
            -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
            -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=ON \
            -DHDF5_ENABLE_SZIP_ENCODING:BOOL=ON \
            -DHDF5_ENABLE_ZLIB_SUPPORT:BOOL=ON \
            -DSITE:STRING=obsd-7.8 \
            ..
            ctest -D Experimental -C Debug
