name: doxygen gh-pages miktex

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ develop ]
    paths-ignore:
      - '.github/CODEOWNERS'
      - '.github/FUNDING.yml'
      - 'doc/**'
      - 'release_docs/**'
      - 'ACKNOWLEDGEMENTS'
      - 'COPYING**'
      - '**.md'

# Using concurrency to cancel any in-progress job or run
concurrency:
  group: ${{ github.workflow }}-${{ github.sha || github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Get Sources
        uses: actions/checkout@v4.1.1

      - name: Install Dependencies
        run: |
          curl -fsSL https://miktex.org/download/key | sudo tee /usr/share/keyrings/miktex-keyring.asc > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/miktex-keyring.asc] https://miktex.org/download/ubuntu jammy universe" | sudo tee /etc/apt/sources.list.d/miktex.list
          sudo apt update -y
          sudo apt install -y libunwind-dev
          sudo apt install -y graphviz
          sudo apt install -y --no-install-recommends doxygen
          sudo apt install -y cmake
          sudo apt install -y miktex
          sudo miktexsetup --shared=yes finish

      - name: Build Develop Documentation
        run: |
          mkdir build
          cd build
          cmake -DHDF5_BUILD_DOC:BOOL=ON ..
          make doxygen
          pwd
          ls -l hdf5lib_docs
          cd hdf5lib_docs/html
          touch .nojekyll
          cd ../latex
          make

      - name: Deploy Develop
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: /home/runner/work/hdf5/hdf5/build/hdf5lib_docs/html
          destination_dir: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}

