name: fbsd d

on:
  push:
    branches:
      - develop-

jobs:
  test: # make sure the action works on a clean machine without building
    name: ${{ matrix.os.name }} ${{ matrix.os.architecture }} ${{ matrix.os.version }} on ${{ matrix.os.host }}
    runs-on: ${{ matrix.os.host }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: freebsd
            architecture: x86-64
            version: '14.0'
            host: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: ${{ matrix.os.name }}
        uses: cross-platform-actions/action@v0.23.0
        with:
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: '${{ matrix.os.version }}'
          shell: bash
          run: |
            sudo pkg install -y git
            sudo pkg install -y cmake
            mkdir build
            cd build
            cmake \
            -DBUILDNAME:STRING=d \
            -D CTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
            -D SITE:STRING=fbsd ..                        
            ctest -D Experimental -C Debug
