name: fuzz hk
on:
  push:
    branches:
      - develop-
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: hyoklee/oss-fuzz
      - name: Build Fuzzers
        id: build
        uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
        with:
          oss-fuzz-project-name: 'hdf5'
          sanitizer: 'memory'
          dry-run: false
          keep-unaffected-fuzz-targets: true
          project-src-path: "${{ runner.workspace }}/hdf5/projects/hdf5"
      - name: Run Fuzzers
        uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
        with:
          oss-fuzz-project-name: 'hdf5'
          fuzz-seconds: 600
          output-sarif: true
          sanitizer: 'memory'
          dry-run: false
          project-src-path: "${{ runner.workspace }}/hdf5/projects/hdf5"