name: fuzz hk
on:
  push:
    branches:
      - develop-

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
        with:
          repository: hyoklee/oss-fuzz
      - name: Build Fuzzers
        id: build
        uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@a068ebf54a1caecb36a7fae35db217ba7e0d93b6 # master
        with:
          oss-fuzz-project-name: 'hdf5'
          sanitizer: 'memory'
          dry-run: false
          keep-unaffected-fuzz-targets: true
          project-src-path: "${{ runner.workspace }}/hdf5/projects/hdf5"
      - name: Run Fuzzers
        uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@a068ebf54a1caecb36a7fae35db217ba7e0d93b6 # master
        with:
          oss-fuzz-project-name: 'hdf5'
          fuzz-seconds: 600
          output-sarif: true
          sanitizer: 'memory'
          dry-run: false
          project-src-path: "${{ runner.workspace }}/hdf5/projects/hdf5"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
