name: i386 alpine

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup alpine
        uses: jirutka/setup-alpine@v1
        with:
          arch: x86
          packages: >
            build-base
            libgit2-dev
            cmake
      - name: run script
        run: |
          cat /etc/os-release
          mkdir build
          cd build
          cmake -DSITE:STRING=alp.i386 -DBUILDNAME:STRING="r" -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" -DCTEST_DROP_LOCATION_INIT="/submit.php?project=HDF5" ..
          ctest -D Experimental -C Release
        shell: bash
