name: lin ndk

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Install Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      - name: Checkout HDF5
        uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir build

      - name: Configure
        working-directory: build
        run: |
          cmake \
          -DCMAKE_TOOLCHAIN_FILE=/usr/local/lib/android/sdk/ndk/27.0.12077973/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DBUILDNAME:STRING=ndk27.0 \
          -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
          -DSITE:STRING=arm64-v8a \
          ..

      - name: Build
        working-directory: build
        run: ctest -T Build
