name: lin gcc_arm64 cpp

on:
  push:
    branches: develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
        sudo apt-get install binfmt-support qemu-system qemu-user-static
        sudo apt-get install musl-dev gcc-aarch64-linux-gnu
    - name: get
      uses: actions/checkout@v5.0.0
    - name: build
      run: |
        echo $PWD
        aarch64-linux-musl-gcc --version
        mkdir build
        cd build
        cmake -DCMAKE_C_COMPILER=aarch64-linux-musl-gcc -DCMAKE_AR=aarch64-linux-musl-ar -DCMAKE_SYSTEM_PROCESSOR=arm -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF -DHDF5_BUILD_CPP_LIB:BOOL=True ..
        make
        make test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
