name: lin spack ompi f

on:
  push:
    branches:
      - develop-

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Fortran
      uses: fortran-lang/setup-fortran@2a1b9c55897d827a9dfeb114408f3615e53b2b72 # v1
      with:
        compiler: gcc
        version: 13
    - name: Checkout spack
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        repository: spack/spack
        path: ./spack
    - name: Run a multi-line script
      run: |
        . ./spack/share/spack/setup-env.sh
        spack spec hdf5@develop-+mpi+fortran
        spack install hdf5@develop-+mpi+fortran

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
