name: lin gcc_min

on:
  push:
    branches: develop-

permissions: read-all

jobs:
  gcc_min:
    name: lin gcc_min
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y mingw-w64 mingw-w64-tools wine64
      - name: Get Source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
      - name: Test HDF5
        run: |
          mkdir build
          cd build
          cmake --toolchain ../config/toolchain/mingw64.cmake \
          -DBUILDNAME:STRING=gcc_min \
          -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
          -DSITE:STRING=lin \
           ..
          # ctest -D Experimental
          ctest -T Build
          ctest -T Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
