name: lin spack ompi f

on:
  push:
    branches:
      - develop-

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Fortran
      uses: fortran-lang/setup-fortran@195bac823dc6e05bb7c706311ad4540ffc34d5b9 # v1
      with:
        compiler: gcc
        version: 13
    - name: Checkout spack
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
      with:
        repository: spack/spack
        path: ./spack
    - name: Run a multi-line script
      run: |
        . ./spack/share/spack/setup-env.sh
        spack spec hdf5@develop-+mpi+fortran
        spack install hdf5@develop-+mpi+fortran

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
