name: Linux Analyzer & Formatter Tools

# Test building with analyzer and formatter tools enabled
# Tests: HDF5_ENABLE_ANALYZER_TOOLS=ON, HDF5_ENABLE_FORMATTERS=ON

on:
  workflow_dispatch:
  push:
    branches: develop-
  pull_request:
    branches: develop-

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: "Ubuntu Analyzer & Formatter"
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build clang-format clang-tidy
          sudo apt install gcc-12 g++-12
          echo "CC=gcc-12" >> $GITHUB_ENV
          echo "CXX=g++-12" >> $GITHUB_ENV

      - name: Install CMake
        uses: lukka/get-cmake@4a7d025fc60f00db0c7b44ebf783d19b52444830 # latest
        with:
          cmakeVersion: latest
          ninjaVersion: latest

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - name: Configure CMake
        run: |
          mkdir "${{ runner.workspace }}/build"
          cd "${{ runner.workspace }}/build"
          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DHDF5_ENABLE_ANALYZER_TOOLS:BOOL=ON \
            -DHDF5_ENABLE_FORMATTERS:BOOL=ON \
            -DBUILD_SHARED_LIBS:BOOL=ON \
            -DHDF5_BUILD_CPP_LIB:BOOL=ON \
            -DHDF5_BUILD_FORTRAN:BOOL=OFF \
            -DHDF5_BUILD_JAVA:BOOL=OFF \
            -DHDF5_BUILD_HL_LIB:BOOL=ON \
            -DHDF5_ENABLE_ZLIB_SUPPORT:BOOL=OFF \
            -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF \
            $GITHUB_WORKSPACE
        shell: bash

      - name: Build
        run: cmake --build . --config Debug
        working-directory: ${{ runner.workspace }}/build

      - name: Test
        run: ctest --build-config Debug --output-on-failure -j2
        working-directory: ${{ runner.workspace }}/build
