name: linux CMake aarch64-gcc

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
jobs:
  aarch64_job:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: Build on ubuntu-latest aarch64
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu_latest

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}
          install: |
            apt-get update -q -y
            apt-get install -q -y git
            apt-get install -q -y cmake
            apt-get install -q -y gcc-aarch64-linux-gnu            
          run: |
            echo ::set-output name=uname::$(uname -a)
            git clone https://github.com/hyoklee/hdf5
            cd hdf5
            mkdir build
            cd build
            cmake -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_AR=aarch64-linux-gnu-ar ..
            make
            make test

      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
