name: linux autotools

on:
  push:
    branches: [ develop ]
  workflow_dispatch:    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: sudo apt-get install ninja-build autoconf automake libtool libtool-bin openmpi
    - name: Get Source
      uses: actions/checkout@v2
    - name: Build and test
      env:
        NPROCS: 3
      run: |
        set
        ./autogen.sh
        ./configure --enable-parallel CC=mpicc
        make
        make check

    
