name: mac-13 CMake clang15 debug gfortran mpich sf

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:
  build:
    strategy:
      matrix:
        name: ["macOS Latest Clang"]
        include:
          - name: "macOS Latest Clang"
            artifact: "macOS.tar.xz"
            os: macos-13
            build_type: "Debug"
            cpp: OFF
            fortran: ON
            java: ON
            ts: OFF
            hl: ON
            parallel: ON
            toolchain: "config/toolchain/clang.cmake"
            generator: "-G Ninja"

    name: ${{ matrix.name }}
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    steps:
    - name: Install Dependencies (macOS)
      run: brew install ninja mpich bash

    - name: Set Bash as the default shell
      run: echo "/usr/local/bin/bash" >> ~/.bashrc

    - name: Install gfortran
      uses: awvwgk/setup-fortran@v1

    - name: Get Sources
      uses: actions/checkout@v4.1.1

    - name: Configure
      if: matrix.generator != 'autogen'
      run: |
        export CC=$(brew --prefix llvm@15)/bin/clang
        echo $CC
        mkdir "${{ runner.workspace }}/build"
        cd "${{ runner.workspace }}/build"
        cmake ${{ matrix.generator }} \
        -DBUILD_SHARED_LIBS=ON \
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
        -DCMAKE_TOOLCHAIN_FILE=${{ matrix.toolchain }} \
        -DHDF5_BUILD_CPP_LIB:BOOL=${{ matrix.cpp }} \
        -DHDF5_BUILD_JAVA=${{ matrix.java }} \
        -DHDF5_BUILD_FORTRAN:BOOL=ON \
        -DHDF5_BUILD_HL_LIB:BOOL=${{ matrix.hl }} \
        -DHDF5_ENABLE_ALL_WARNINGS=ON \
        -DHDF5_ENABLE_PARALLEL:BOOL=${{ matrix.parallel }} \
        -DHDF5_ENABLE_THREADSAFE:BOOL=${{ matrix.ts }} \
        -DHDF5_ENABLE_SUBFILING_VFD:BOOL=ON \
        -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF \
        -DMPIEXEC_MAX_NUMPROCS:STRING=2 \
        $GITHUB_WORKSPACE
      shell: bash

    - name: Build
      run: cmake --build . --config ${{ matrix.build_type }}
      working-directory: ${{ runner.workspace }}/build

    - name: Test
      run: |
        ctest --build . -C ${{ matrix.build_type }} \
        -E MPI_TEST_H5DIFF-h5diff -VV --output-on-error
      working-directory: ${{ runner.workspace }}/build
      shell: bash