name: mac auto ompi

on:
  push:
    branches:
      - develop-

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Install Dependencies
      run: brew install ninja autoconf automake libtool openmpi
    - name: Get Source
      uses: actions/checkout@v4.1.1
    - name: Build and test
      env:
        NPROCS: 2
      run: |
        set
        ./autogen.sh
        ./configure --enable-parallel CC=mpicc
        make
        make check

    
