name: mac-13 CMake clang15 Xcode

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Generate Xcode project
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: brew install curl openssl libaec mpich
      - name: Generate Xcode project
        run: |
          export OPENSSL_ROOT_DIR=/usr/local/Cellar/openssl@3/3.1.1
          export CC=$(brew --prefix llvm@15)/bin/clang
          echo $CC
          mkdir build
          cd build
          cmake -DHDF5_ENABLE_ROS3_VFD:BOOL=ON -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF -DHDF5_ENABLE_PARALLEL:BOOL=ON -DHDF5_BUILD_PARALLEL_TOOLS:BOOL=ON  -G Xcode ..
          cmake --build . --config Debug
          ctest --build . -C Debug
          sudo cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_CONFIG_NAME=Debug  -P cmake_install.cmake

