name: mac autotools

on:
  push:
    branches: [ develop ]
  workflow_dispatch:    
jobs:
  build:
    runs-on: macos-11
    steps:
    - name: Install Dependencies
      run: brew install ninja autoconf automake libtool openmpi
    - name: Get Source
      uses: actions/checkout@v2
    - name: Build and test
      run: |
        ./autogen.sh
        ./bin/chkmanifest
        ./configure --enable-parallel
        make
        make check

    
