name: mac spack h5py

on:
  push:
    branches:
      - develop-

permissions: read-all

jobs:
  build:
    runs-on: macos-latest

    steps:

    - name: Install gfortran
      uses: awvwgk/setup-fortran@2a1b9c55897d827a9dfeb114408f3615e53b2b72 # v1

    - name: Checkout Spack
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        repository: spack/spack
        path: ./spack

    - name: Run a multi-line script
      run: |
        sed -i '' 's/hdf5@1.8.4:1.14/hdf5@1.8.4:/g' ./spack/var/spack/repos/builtin/packages/py-h5py/package.py
        ./spack/bin/spack compiler find
        ./spack/bin/spack external find perl
        ./spack/bin/spack install py-h5py@master+mpi ^openblas@develop-
        ./spack/bin/spack install py-pytest
        ./spack/bin/spack install py-ipython
        . ./spack/share/spack/setup-env.sh
        spack load py-h5py
        spack load py-pytest
        spack load py-ipython
        pip install pytest-mpi
        python -c "import h5py; h5py.run_tests(); print(h5py.version.info);"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
