name: msys2

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ develop ]
    paths-ignore:
      - '.github/CODEOWNERS'
      - '.github/FUNDING.yml'
      - 'doc/**'
      - 'release_docs/**'
      - 'ACKNOWLEDGEMENTS'
      - 'COPYING**'
      - '**.md'

permissions:
  contents: read

# Using concurrency to cancel any in-progress job or run
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        sys:
          - mingw64
          - mingw32
          - ucrt64
          - clang64
    runs-on: windows-latest
    steps:
      - name: git
        run: git config --global core.autocrlf input
      - name: get
        uses: actions/checkout@v4
      - name: '${{ matrix.icon }} set'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p
      - name: build
        shell: msys2 {0}
        run: |
          mkdir build
          cd build
          cmake -DH5_HAVE_ALARM:INTERNAL=0 -DH5_HAVE_ASPRINTF:INTERNAL=0 -DH5_HAVE_VASPRINTF:INTERNAL=0 ..
          ninja
#          ninja test
