name: msys2 auto

# Triggers the workflow on a call from another workflow
on:
  workflow_call:
  push:
    branches:
      - develop-  
  pull_request:
    branches: [ develop ]
    paths-ignore:
      - '.github/CODEOWNERS'
      - '.github/FUNDING.yml'
      - 'doc/**'
      - 'release_docs/**'
      - 'ACKNOWLEDGEMENTS'
      - 'COPYING**'
      - '**.md'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  msys2_build_and_test:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { icon: '⬛', sys: mingw32 }
          - { icon: '🟦', sys: mingw64 }
          - { icon: '🟨', sys: ucrt64  }
          - { icon: '🟧', sys: clang64 }
    name: ${{ matrix.icon }} msys2-${{ matrix.sys }}
    steps:
      - name: git
        run: git config --global core.autocrlf input

      - name: get
        uses: actions/checkout@v4.1.7

      - name: '${{ matrix.icon }} set'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: >-
            git
            autotools
          pacboy: >-
            toolchain:p

      - name: configure
        shell: msys2 {0}
        run: |
          ./autogen.sh
          ./configure LDFLAGS="-lws2_32"

      - name: build
        shell: msys2 {0}
        run: |
          make

#      - name: test
#        run: |
#          make check -j
#        working-directory: $GITHUB_WORKSPACE/build
