name: ompi

on: [push, pull_request]

jobs:
  test:
    name: ompi
    runs-on: ubuntu-latest
    steps:
      - name: get
        uses: actions/checkout@v4
        with:
          repository: HDFGroup/hdf5
          path: .

      - name: test
        uses: cross-platform-actions/action@v0.23.0
        env:
          FOO: A
          BAR: B
        with:
          environment_variables: FOO BAR
          operating_system: openbsd
          architecture: x86-64
          version: '7.4'
          shell: bash
          run: |
            sudo pkg_add cmake
            sudo pkg_add openmpi
            export NPROCS=2
            mkdir build
            cd build
            cmake -DBUILDNAME:STRING=ompi \
            -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
            -DHDF5_ENABLE_PARALLEL:BOOL=ON \
            -DMPIEXEC_PREFLAGS="-oversubscribe" \
            -DSITE:STRING=obsd \
            ..
            ctest -D Experimental
