name: OpenBSD 7.2 CMake

on:
  push:
    branches: [develop]

jobs:
  test:
    runs-on: macos-12
    name: A job to run test in OpenBSD
    env:
      MYTOKEN : "value1"
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: Test in OpenBSD
      id: test
      uses: vmactions/openbsd-vm@v0
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: |
          pkg_add git
        run: |
          pkg_add cmake        
          pwd
          ls
          cd ..
          mv hdf5 /home
          cd /home/hdf5
          pwd
          ls
          mkdir build
          cd build
          cmake ..
          make
          make test
          
