name: r

on:
  push:
    branches:
      - develop-

jobs:
  test:
    name: ${{ matrix.os.name }} ${{ matrix.os.architecture }} ${{ matrix.os.version }} on ${{ matrix.os.host }}
    runs-on: ${{ matrix.os.host }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: openbsd
            architecture: x86_64
            version: '7.6'
            host: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ${{ matrix.os.name }}
        uses: cross-platform-actions/action@master
        env:
          FOO: A
          BAR: B
        with:
          environment_variables: FOO BAR
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: '${{ matrix.os.version }}'
          shell: bash
          run: |
            sudo pkg_add cmake
            mkdir build
            cd build
            cmake \
            -DBUILDNAME:STRING="hk/r" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCTEST_DROP_LOCATION_INIT="/submit.php?project=HDF5" \
            -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
            -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF \
            -DSITE:STRING=obsd \
            ..
            ctest -D Experimental -C Release