name: riscv64 lin

on:
  push:
    branches:
      - develop-

permissions: read-all

jobs:
  riscv64_job:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: Build on ubuntu-latest riscv64
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
      - uses: uraimo/run-on-arch-action@fd7aa8593480287702b446a273a68f788a9bad3a # v3
        name: Run commands
        id: runcmd
        with:
          arch: riscv64
          distro: ubuntu_latest
          install: |
            apt-get update -q -y
            apt-get install -q -y git
            apt-get install -q -y cmake
          run: |
            mkdir build
            cd build
            cmake -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF ..
            make
            make test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
