name: s390x lin f

on:
  push:
    branches:
      - develop-

permissions: read-all

jobs:
  s390x_job:
    name: s390x lin f
    runs-on: ubuntu-latest

    steps:
      - name: Get Sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - name: Run
        uses: uraimo/run-on-arch-action@fd7aa8593480287702b446a273a68f788a9bad3a # v3
        id: runcmd
        with:
          arch: s390x
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          install: |
            apt-get update -q -y
            apt-get install -q -y git cmake libjpeg-dev zlib1g zlib1g-dev
            apt-get install -q -y gfortran g++  yacc flex libtool autotools-dev
          run: |
            echo ::set-output name=uname::$(uname -a)
            mkdir build
            cd build
            cmake \
            -DBUILDNAME:STRING="hk/f" \
            -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" \
            -DHDF5_BUILD_FORTRAN:BOOL=ON \
            -DBUILD_SHARED_LIBS:BOOL=OFF \
             -DSITE:STRING=s390x \
            ..
            ctest -D Experimental
            # ctest -T Build
            # ctest -T Test

      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
