name: sol

on:
  push:
    branches: develop
defaults:
  run:
    shell: bash

permissions: read-all

jobs:
  build:
    name: solaris-${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: gcc
            release: "11.4-gcc"
            cc: gcc
            cxx: g++
          - name: clang-19
            release: "11.4-clang-19"
            cc: clang
            cxx: clang++
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: test
        uses: vmactions/solaris-vm@315163f088b66e55bbcc45928bd224d4973b2312 # v1.3.8
        with:
          release: "${{ matrix.release }}"
          usesh: true
          copyback: false
          run: |
            ${{ matrix.cc }} --version
            ${{ matrix.cxx }} --version
            find . -name "CMakeLists.txt" -print0 | xargs -0 perl -pi.bak -e 's/VERSION 3\.26/VERSION 3\.24/g'
            mkdir build
            cd build
            cmake -DSITE:STRING="sol" -DBUILDNAME:STRING="hk/r/${{ matrix.name }}" -DCMAKE_C_COMPILER=${{ matrix.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" -DCTEST_DROP_LOCATION_INIT:STRING="/submit.php?project=HDF5" -DCMAKE_BUILD_TYPE=Release  ..
            ctest -D Experimental -C Release
            # ctest -T Build
            # ctest -T Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
