name: spack

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events for the develop branch
  push:
    branches: [ develop ]
    paths-ignore:
    - '.github/**'
    - 'doc/**'
    - 'release_docs/**'
  pull_request:
    branches: [ develop ]
  # Allows you to run this workflow manually from the Actions tab    
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Spack
      uses: actions/checkout@v2
      with:
        repository: hyoklee/spack
        path: ./spack

    - name: Install dependencies
      run: sudo apt-get install ninja-build automake autoconf libtool libtool-bin bison flex

    - name: Run a multi-line script
      run: |
        ./spack/bin/spack install hdf5-cmake
        ./spack/bin/spack install py-h5py ^openblas@develop
        ./spack/bin/spack install py-pytest
        ./spack/bin/spack install py-ipython
        ./spack/bin/spack install py-pip
        . ./spack/share/spack/setup-env.sh
        spack load py-h5py
        spack load py-pytest
        spack load py-ipython
        spack load py-pip
        pip install pytest-mpi
        python -c "import h5py; h5py.run_tests()"
