name: win ninja icx ifx p

on:
  push:
    branches:
      - develop-

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: cmake
        uses: lukka/get-cmake@latest
      - name: oneapi
        uses: awvwgk/setup-fortran@main
        with:
          compiler: intel
          version: '2024.1'
      - name: mpi
        uses: mpi4py/setup-mpi@master
        with:
          mpi: intelmpi
      - name: checkout
        uses: actions/checkout@v4.1.1
      - name: vars
        shell: cmd
        run: |
          "C:/Program Files (x86)/Intel/oneAPI/mpi/latest/env/vars.bat"
      - name: test
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DHDF5_BUILD_FORTRAN:BOOL=ON -DHDF5_ENABLE_PARALLEL:BOOL=ON -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF -DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=OFF -DMPIEXEC_EXECUTABLE:FILEPATH="C:\Program Files (x86)\Intel\oneAPI\mpi\2021.12\bin\mpiexec.exe" -DMPI_C_HEADER_DIR:PATH="C:\Program Files (x86)\Intel\oneAPI\mpi\2021.12\include" -DCTEST_DROP_SITE_INIT=my.cdash.org -DSITE=win -DBUILDNAME="ninja/icx/+f/+p" ..
#          ctest -D Experimental -C Release	  
