name: win ninja icx ifx sh

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: cmake
        uses: lukka/get-cmake@latest
      - name: ifx
        uses: awvwgk/setup-fortran@main
        with:
          compiler: intel
          version: '2024.1'
      - name: checkout
        uses: actions/checkout@v4.1.1
      - name: test
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_C_COMPILER="C:/Program Files (x86)/Intel/oneAPI/compiler/2024.1/bin/icx.exe" -DCMAKE_Fortran_COMPILER="C:/Program Files (x86)/Intel/oneAPI/compiler/2024.1/bin/ifx.exe" -DHDF5_BUILD_FORTRAN:BOOL=ON -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF -DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=OFF -DCTEST_DROP_SITE_INIT=my.cdash.org -DSITE=win -DBUILDNAME="ninja/icx/+f" ..
          ctest -D Experimental -C Release
