name: win 2025

on:
  push:
    branches: develop
jobs:
  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v5.0.0
      - name: libaec
        run: |
          vcpkg install libaec
      - name: zlib
        run: |
          vcpkg install zlib
      - name: integrate
        run: |
          vcpkg integrate install
      - name: test
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 -DSITE:STRING="win-25" -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DBUILDNAME:STRING="vcpkg/r+zl+sz" -DCTEST_DROP_SITE_INIT:STRING="my.cdash.org" -DCTEST_DROP_LOCATION_INIT="/submit.php?project=HDF5"  ..
          # ctest -D Experimental -C Release
          ctest -T Build
          ctest -C Release -T Test
        shell: cmd

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
