name: win ninja icx ifx

on:
  push:
    branches:
      - develop-

permissions: read-all

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: cmake
        uses: lukka/get-cmake@4a7d025fc60f00db0c7b44ebf783d19b52444830 # latest
      - name: ifx
        uses: awvwgk/setup-fortran@195bac823dc6e05bb7c706311ad4540ffc34d5b9 # main
        with:
          compiler: intel
          version: '2024.1'
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
      - name: test
        shell: cmd
        run: |
          set
          mkdir build
          cd build
          cmake -G Ninja -DBUILD_SHARED_LIBS:BOOL=OFF -DHDF5_BUILD_FORTRAN:BOOL=ON -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF -DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=OFF  -DCTEST_DROP_SITE_INIT=my.cdash.org -DSITE=win -DBUILDNAME="ninja/icx/+f/-sh" ..
          # ctest -D Experimental -C Release
          ctest -T Build
          ctest -T Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
