name: win ninja icx ifx sh

on:
  push:
    branches:
      - develop-

permissions: read-all

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: cmake
        uses: lukka/get-cmake@591817e96fcad43505fb4eae36172462abb3a42e # latest
      - name: ifx
        uses: awvwgk/setup-fortran@6e78ae7d5259eeee47a5fdc1dc6cd2a450c5f54d # main
        with:
          compiler: intel
          version: '2024.1'
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: test
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_C_COMPILER="C:/Program Files (x86)/Intel/oneAPI/compiler/2024.1/bin/icx.exe" -DCMAKE_Fortran_COMPILER="C:/Program Files (x86)/Intel/oneAPI/compiler/2024.1/bin/ifx.exe" -DHDF5_BUILD_FORTRAN:BOOL=ON -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF -DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=OFF -DCTEST_DROP_SITE_INIT=my.cdash.org -DSITE=win -DBUILDNAME="ninja/icx/+f" ..
          # ctest -D Experimental -C Release
          ctest -T Build
          ctest -T Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
