name: win ninja icx

on:
  push:
    branches:
      - develop-

permissions: read-all

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@f5b8fbb4d77cec1acc5a5f9f0df4beffaf5d98d9 # latest
        with:
          cmakeVersion: latestrc
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@ebc0426251bc40c7cd31162802432c68818ab8f0 # v2
        with:
          version: "17"
      - name: Install Intel OneAPI
        uses: awvwgk/setup-fortran@2a1b9c55897d827a9dfeb114408f3615e53b2b72 # main
        with:
          compiler: intel
          version: '2024.1'
      - name: Checkout HDF5
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
      - name: Set oneAPI
        shell: cmd
        run: |
          "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"
      - name: Configure & Build & Test
        shell: cmd
        run: |
          cd hdf5
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_C_COMPILER="C:/Program Files (x86)/Intel/oneAPI/compiler/latest/bin/icx.exe" -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF -DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=OFF ..
          ninja
          ninja test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
